# Generated by Django 2.2 on 2020-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=50)),
                ('formData', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
